Import into external_persons
06/04/19 02:22:11

0 out of 2 records processed successfully.
0 records added.
0 records updated.
2 records processed with errors:

Field 'created_by_id' doesn't have a default value
"1","1","test","test_person","1","4","","","2","Derp","","Derpson","","","","","derp@derpson.com","","","","","","","","","","","",""

Field 'created_by_id' doesn't have a default value
"2","2","test","test_person","1","4","","","3","Derpina","","Derpson","","","","","derpina@derp.com","","","","","","","","","","","",""